---
title: "Assignment 3"
author: "Taylor McKinley"
date: "September 24, 2018"
output: word_document
---

Reading in the data
```{r}
library(ggplot2)
titanic = read.csv("titanic.csv")
titanic$Survived = factor(titanic$Survived)
titanic$Pclass = factor(titanic$Pclass)
str(titanic)

```
#1 
```{r}
#is.na(titanic)
sum(is.na(titanic))
sum(is.na(titanic$Age))
sum(is.na(titanic$PassengerId))
sum(is.na(titanic$Sibsp))
sum(is.na(titanic$Cabin))
```
#2 
```{r}
titanic[is.na(titanic$Age),]$Age = mean(titanic$Age, na.rm = TRUE)


```
#3
```{r}
titanic[, "Cabin"] = NULL

```

#4
```{r}
titanic$name = NULL 
titanic$ticket = NULL
```

#5
```{r}
mean(titanic$Age)

```

#6
```{r}
#titanic$Sex
mean(titanic[titanic$Sex=="female",]$Age)
```

#7
```{r}
#titanic$Pclass
median(titanic[titanic$Pclass==1,]$Fare)
```

#8
```{r}
median(titanic[(titanic$Sex=="female")&(titanic$Pclass!=1),]$Fare)

```

#9 
```{r}
median(titanic[(titanic$Sex=="female")&(titanic$Survived==1)&((titanic$Pclass==1)|(titanic$Pclass==2)),]$Age)

```

#10
```{r}
mean(titanic[(titanic$Sex=="female")&(titanic$Survived==1)&((titanic$Age >= 13)&(titanic$Age < 20)),]$Fare)

```

#11
```{r}
mean(titanic[(titanic$Sex=="female")&(titanic$Survived==1)&((titanic$Age >= 13)&(titanic$Age < 20))&(titanic$Pclass==1),]$Fare)
mean(titanic[(titanic$Sex=="female")&(titanic$Survived==1)&((titanic$Age >= 13)&(titanic$Age < 20))&(titanic$Pclass==2),]$Fare)
mean(titanic[(titanic$Sex=="female")&(titanic$Survived==1)&((titanic$Age >= 13)&(titanic$Age < 20))&(titanic$Pclass==3),]$Fare)

```

#12
```{r}
t1 = titanic[titanic$Fare>mean(titanic$Fare),]
prop.table(table(t1$Survived))

```

#13
```{r}
titanic$newcol = titanic$Fare - (mean(titanic$Fare)/sd(titanic$Fare))
titanic$newcol
```

#14
```{r}
ggplot(t1) + geom_bar(mapping = aes(x = Sex, fill = Survived))

```


#15
```{r}
ggplot(t1) + geom_density(mapping =  aes(x = Survived))

```

#16 -- got an error
```{r}
#ggplot(titanic) + geom_density(titanic[Embarked == "S"|(Embarked == "Q"]mapping =  aes(x = Embarked))

```

#17
```{r}
 titanic$cfare[titanic$Fare < mean(titanic$Fare)] = 0
 titanic$cfare[titanic$Fare > mean(titanic$Fare)] = 1
 titanic$cfare[titanic$Fare < mean(titanic$Fare)] = "cheap"
 titanic$cfare[titanic$Fare > mean(titanic$Fare)] = "expensive"
```

#18
```{r}
 titanic$cage[titanic$Age >= 0 & titanic$Age <= 10] = 0
 titanic$cage[titanic$Age >= 11 & titanic$Age <= 20] = 1
 titanic$cage[titanic$Age >= 21 & titanic$Age <= 30] = 2
 titanic$cage[titanic$Age >= 31 & titanic$Age <= 40] = 3
 titanic$cage[titanic$Age >= 41 & titanic$Age <= 50] = 4
 titanic$cage[titanic$Age >= 51 & titanic$Age <= 60] = 5
 titanic$cage[titanic$Age >= 61 & titanic$Age <= 70] = 6
 titanic$cage[titanic$Age >= 71 & titanic$Age <= 80] = 7
```

#19 -- got an error
```{r}
#ggplot(titanic) + geom_bar(data = titanic[titanic$Fare > mean(titanic$Fare),]
                                         # mapping = aes(x = titanic$cage, fill = Survived))
```

#20 -- got an error
```{r}
 #ggplot(titanic) + geom_bar(data = titanic[titanic$Fare > mean(titanic$Fare),]
 #mapping = aes(x = titanic$cage, fill = Survived)) + facet_wrap(~ age)
```